media:
  input: biczycki/aid4hate
  output: biczycki/aid4hate

collections:
  - id: pages
    label: Seiten
    type: folder
    path: content
    format: md
    fields:
      - name: title
        label: Titel
        type: string
      - name: body
        label: Inhalt
        type: rich-text
